### ISSUE TITLE
Got Dis issue with latest Pinkie's proxy

### ISSUE THREAD

**Issue by Reny900** [Mister-Kay/commands-list#1]
```cmd
ReferenceError: p is not defined
    at eval (eval at getCommands (M:\Tera_proxy\Pinkie-proxy\bin\node_modules\commands-list\index.js:75:39), <anonymous>:1:1)
    at getCommands (M:\Tera_proxy\Pinkie-proxy\bin\node_modules\commands-list\index.js:75:39)
    at fs.readdir (M:\Tera_proxy\Pinkie-proxy\bin\node_modules\commands-list\index.js:50:25)
    at FSReqCallback.oncomplete (fs.js:148:20)
```
Dunno if this only works only with Caali's version since its not stated in the readme.
keep up the god's work!

p.s. upon further usage, the module its working itself, so no idea what that is

**Comment by ghost** [comment]
Thanks for the report. I accidentally left that debug message from the command finder's false-positive checker. I also found an error in the that checker that still added false positives to the command list. Both should be fixed as of my commit 8 hours ago, so make sure to redownload if you're using pinkie's proxy which does not have auto-update (yet).
